name: CI - Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:js

      - name: Run HTML validation
        run: npm run lint:html

      - name: Check code formatting
        run: npm run format:check
        continue-on-error: true

      - name: Run build
        run: npm run build

  status-check:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    if: always()

    steps:
      - name: Check CI status
        run: |
          if [ "${{ needs.lint-and-test.result }}" != "success" ]; then
            echo "CI checks failed"
            exit 1
          fi
          echo "All CI checks passed!"
